### ISSUE TITLE
kiss_submitter broken 

### ISSUE THREAD

**Issue by thasti** [daniestevez/gr-satellites#1]
The kiss_submitter flow graph is currently broken with the following error message: 
>>> Error: Connection between blocks_socket_pdu_0(pdus) and kiss_kiss_to_pdu_0(in) could not be made. sink key 'in' not in sink block keys

I suspect an API change in gr-kiss, but currently have no good idea on how to fix it. I think it was broken by 4d2a0a2c6 in gr-kiss.

**Comment by daniestevez** [comment]
You are right. It was broken by an API change in gr-kiss and I never noticed, as I don't use that flow graph often. I've just fixed it.

**Comment by thasti** [comment]
Thanks, works for me now ;)
