### ISSUE TITLE
gr_satelliets can't upload EO-88 telemetry to FUNcube warehouse

### ISSUE THREAD

**Issue by jh4xsy** [daniestevez/gr-satellites#109]
I'm using gr-satellites v3.0.0-rc1.
FUNcube warehouse accepted AO-73 but not EO-88.
I found typo in Nayif-1.yml and JY1-Sat.yml.
"telmetry_servers:" should be "telemetry_servers:".

**Comment by daniestevez** [comment]
Thanks for noticing!
I'm fixing this and adding a test so that this kind of errors don't go unnoticed.
