### ISSUE TITLE
make test fails on a WSL environment. 

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#116]
When running a distro on the Windows Linux subsystem the make test fails.
When executing ctest -V the reaon is that both .sh scripts try to add a PATH setting that has a space in it.

make test
Running tests...
Test project /home/janvg/source/git/daniestevez/gr-satellites/build
    Start 1: qa_ao40_fec_deframer
1/2 Test #1: qa_ao40_fec_deframer .............***Failed    0.00 sec
    Start 2: qa_satyaml
2/2 Test #2: qa_satyaml .......................***Failed    0.00 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - qa_ao40_fec_deframer (Failed)
          2 - qa_satyaml (Failed)
Errors while running CTest
make: *** [Makefile:130: test] Error 8

ctest -V
UpdateCTestConfiguration  from :/home/janvg/source/git/daniestevez/gr-satellites/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/janvg/source/git/daniestevez/gr-satellites/build/DartConfiguration.tcl
Test project /home/janvg/source/git/daniestevez/gr-satellites/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: qa_ao40_fec_deframer

1: Test command: /bin/sh "/home/janvg/source/git/daniestevez/gr-satellites/build/python/components/deframers/qa_ao40_fec_deframer_test.sh"
1: Test timeout computed to be: 10000000
1: /home/janvg/source/git/daniestevez/gr-satellites/build/python/components/deframers/qa_ao40_fec_deframer_test.sh: **6: export: (x86)/Common: bad variable name**
1/2 Test #1: qa_ao40_fec_deframer .............***Failed    0.00 sec
test 2
    Start 2: qa_satyaml

2: Test command: /bin/sh "/home/janvg/source/git/daniestevez/gr-satellites/build/python/satyaml/qa_satyaml_test.sh"
2: Test timeout computed to be: 10000000
2: /home/janvg/source/git/daniestevez/gr-satellites/build/python/satyaml/qa_satyaml_test.sh: 6: export: (x86)/Common: bad variable name
2/2 Test #2: qa_satyaml .......................***Failed    0.00 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - qa_ao40_fec_deframer (Failed)
          2 - qa_satyaml (Failed)
Errors while running CTest

By placing quotes around the second $PATH variable this is solved.

export PATH="/home/janvg/source/git/daniestevez/gr-satellites/build/python/components/deframers":**"$PATH"**

This needs to be done for both shell scripts.

**Comment by daniestevez** [comment]
The GNU Radio team has fixed the problem and closed the issue I opened, so this can now be closed as well.
