### ISSUE TITLE
BY70-2 Install request

### ISSUE THREAD

**Issue by ik8ozv** [daniestevez/gr-satellites#124]
Hello Please anybody can tell me how to decode the BY70-2 satellite?
i know that i have to give the command:

https://github.com/bg2bhc/gr-lilacsat

in the terminal but i cannot find in the readme how to install
Any help please
Thanks in advance.
73's de Enzo IK8OZV

**Comment by daniestevez** [comment]
Please note that gr-lilacsat and gr-satellites are two different things. I will see what is needed to add support for BY70-2 in gr-satellites probably later today.

**Comment by ik8ozv** [comment]
Fine Daniel so i wait for your Job.
Mucho obrigado
73's de Enzo IK8OZV
