### ISSUE TITLE
--version displays same info as -h

### ISSUE THREAD

**Issue by K4KDR** [daniestevez/gr-satellites#138]
With the most recent MASTER commit to-date (eef6199), the following command:

`gr_satellites --version`

displays the same command help as:

`gr_satellites -h`

... with no mention of the installed version number.

Thanks!

**Comment by daniestevez** [comment]
Hi Scott,

For technical reasons, `gr_satellites` is always intended to be run as `gr_satellites SATELLITE [options]`, so if you run `gr_satellites --version` it is actually complaining that you need to specify a satellite. So the correct way is to specify some satellite. For instance `gr_satellites AO-73 --version` (in the same way, note that `gr_satellites --help` and `gr_satellites AO-73 --help` don't show the same thing).

But maybe this is completely non-obvious, so I might think of a workaround.

**Comment by K4KDR** [comment]
Thank you!!  My mistake.   But yes, I suppose **--version** is somewhat of a standard for many/most linux commands
