### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by keramaisa** [daniestevez/gr-satellites#15]
Hello :)

I have a problem installing gr_satellites, which I cannot solve since few days. I'm working on a ground station development project and it's almost last thing I need to succeed so I will be more then happy if somebody can help me with that !!

So, I've installed gnuradio using apt-get, but also before that I've add all required dependencies and libraries. First I've tried to install gnuradio with pyBOMBS but it was missing a lot of files so I just keep all the pyBOMBS dependencies and add gnuradio with as I said apt-get.

All the depndencies are the latest versions.
So here is the ERROR : 

> CMake Error at CMakeLists.txt:126 (find_package):
>   By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Gnuradio",
>   but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Gnuradio"
>   (requested version 3.7.2) with any of the following names:
> 
>     GnuradioConfig.cmake
>     gnuradio-config.cmake
> 
>   Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
>   "Gnuradio_DIR" to a directory containing one of the above files.  If
>   "Gnuradio" provides a separate development package or SDK, be sure it has
>   been installed.
> 

I'm afraid that my gnuradio installed by apt-get method don't have all the files required by gr8stallites .. I don't know here is the list of files in gnuradio dir : (/etc/gnuradio/conf.d)

> gnuradio-runtime.conf  
> gr-audio-oss.conf       
> gr-qtgui.conf
> gr-audio-alsa.conf     
> gr-audio-portaudio.conf  gr-wxgui.conf
> gr-audio.conf          
> grc.conf                 
> modtool.conf
> gr-audio-jack.conf     
> gr_log_default.conf
> 

I dont't know I also attached CMakeCache.txt file and CMakeOutput.log if someone is patience and want to take a look to help me :)
[CMakeLists.txt](https://github.com/daniestevez/gr-satellites/files/1973834/CMakeLists.txt)
[CMakeOutput.log](https://github.com/daniestevez/gr-satellites/files/1973835/CMakeOutput.log)

So that's all, I will really appreciate any suggestion and help !!

Joanna

**Comment by daniestevez** [comment]
Dear Joanna,

What is the distribution and version you are using and the gnuradio package you installed with apt-get? You should probably search for `.cmake` files inside that gnuradio `.deb` package.

**Comment by keramaisa** [comment]
It's GNU Radio Companion 3.7.10. 
That's the problem I cannot find .cmake files inside gnuradio. I didn't installed it manually. Cause when i tried from source but it was extremally hard to compile for me :/

**Comment by daniestevez** [comment]
What is your distribution again?

**Comment by keramaisa** [comment]
Sorry, its Linux Mint 18.3 Sylvia

**Comment by daniestevez** [comment]
You should also install the package `gnuradio-dev`. This packet contains the `GnuradioConfig.cmake` file (see [here](https://packages.ubuntu.com/search?searchon=contents&keywords=GnuradioConfig.cmake&mode=exactfilename&suite=bionic&arch=any)).

**Comment by keramaisa** [comment]
Okay it works now. Sorry to respond so late and thank you for your help and great packgage :) !
