### ISSUE TITLE
STRaND-1 Decoder

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#151]
I wanted to decode STRaND-1 Telemetry and used GRIFEX.yml as an example, so created the following file.

STRAND-1.yml

name: STRAND-1
norad: 39090
data:
  &tlm Telemetry:
    telemetry: ax25
transmitters:
  9k6 FSK downlink:
    frequency: 437.568e+6
    modulation: FSK
    baudrate: 9600
    framing: AX.25 G3RUH
    data:
    - *tlm

Telemetry example: https://network.satnogs.org/observations/2699592/

**Comment by daniestevez** [comment]
Hi Jan, Thank you! Will you be submitting a pull request with this file or should I add it myself if that's easier for you?

**Comment by janvgils** [comment]
Hi Dani,

I am not comfortable with all the git functions yet, so If you can, please do. 
Looking at other satellites with similar characteristics, so I really need to get familiar with git.

**Comment by daniestevez** [comment]
No worries. I'll do this right away.
