### ISSUE TITLE
install

### ISSUE THREAD

**Issue by EGRAN1** [daniestevez/gr-satellites#155]
I could not complete the installation steps correctly.
!
[cmake hatası](https://user-images.githubusercontent.com/53379482/91547999-637a9700-e92d-11ea-8497-7e936907d562.PNG)

**Comment by daniestevez** [comment]
Note that you are inside a `build` folder in your home directory. The build instructions need to be run inside the `gr-satellites` directory. I have just modified slightly the installation instructions in ec963f9d1cc219ef8d97445e1e6514541ba0f8aa to try to make this more clear.

**Comment by daniestevez** [comment]
I'm closing this, since it has been open for a couple of weeks with no response. Feel free to reopen.
