### ISSUE TITLE
Make test is failed

### ISSUE THREAD

**Issue by ugurcansoruc** [daniestevez/gr-satellites#157]
Hi Daniel, i get an error while testing the make test command, what could be the reason for this?

![satallite](https://user-images.githubusercontent.com/34628280/91645967-10026900-ea53-11ea-8abe-72be822b8e78.png)

**Comment by daniestevez** [comment]
Can you please run `ctest -V` to get a detailed output of the failures?

Also, please include what version of gr-satellites you're building.

**Comment by ugurcansoruc** [comment]
I tried master and main-3.8, both got the same errors.
I am using version 3.8.2.0 (Python 3.6.9) of the gnu radio.
I ran the command Ctest -V, I added the errors I received in errorLog.txt file. 
[errorLog.txt](https://github.com/daniestevez/gr-satellites/files/5153122/errorLog.txt)

**Comment by daniestevez** [comment]
This seems to indicate that the python module wasn't built properly.

To check if it is a problem of the test setup or it is a real problem, please install using `sudo make install` and `sudo ldconfig` and then run `import satellites` inside a `python3` interpreter.

**Comment by ugurcansoruc** [comment]
I reinstalled using miniconda. Problem solved, thank you...
