### ISSUE TITLE
Can't install gr-satellites and gnuradio-dev

### ISSUE THREAD

**Issue by DL8LAQ** [daniestevez/gr-satellites#161]
Hi Daniel,

maybe you or another user can give me a hint to solve this problem. I spend hours searching the net for similar problems and a solution.

 73, Norbert
﻿My systeminfo (always the latest updates)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Gnuradio 3.8.1.0 (Python 3.8.2) from ubuntu-focal-universe

I tried to install gr-satellites according to these instructions:

https://gr-satellites.readthedocs.io/en/latest/installation.html

Depencies:

Checked all, installed Python packages construct and requests

Optional Depencies:

Installed feh

Downloaded https://github.com/daniestevez/gr-satellites/releases/tag/v3.3.0

Building and installing:

$ mkdir build
$ cd build
$ cmake ..

But cmake fails:

shack@radio:~/workspace/gr-satellites-3.3.0/build$ cmake ..
-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:87 (find_package):
  By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Gnuradio",
  but CMake did not find one.

  Could not find a package configuration file provided by "Gnuradio"
  (requested version 3.9) with any of the following names:

    GnuradioConfig.cmake
    gnuradio-config.cmake

  Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
  "Gnuradio_DIR" to a directory containing one of the above files.  If
  "Gnuradio" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/shack/workspace/gr-satellites-3.3.0/build/CMakeFiles/CMakeOutput.log".
shack@radio:~/workspace/gr-satellites-3.3.0/build$

Searching for a solution... Found this:

https://github.com/daniestevez/gr-satellites/issues/68

Changed CmakeLists.txt line 87: ...3.8… to ...3.9…

But cmake does not make it. Same fault!

More searching… Found this:

https://github.com/daniestevez/gr-satellites/issues/15

Tried to install gnuradio-dev:

shack@radio:~/workspace/gr-satellites-3.3.0/build$ sudo apt install gnuradio-dev 
[sudo] password for shack: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 gnuradio-dev : Depends: libvolk2-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Ok, I tried to install libvolk2-dev:

shack@radio:~/workspace/gr-satellites-3.3.0/build$ sudo apt install libvolk2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libvolk2-dev : Depends: libvolk2.2 (= 2.2.1-1) but 2.2.1-2~ubuntu19.10.1~ppa1 is to be installed
E: Unable to correct problems, you have held broken packages.
shack@radio:~/workspace/gr-satellites-3.3.0/build$ 

shack@radio:~/workspace/gr-satellites-3.3.0/build$ apt list | grep libvolk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvolk2-bin/now 2.2.1-2~ubuntu19.10.1~ppa1 amd64 [installed,local]
libvolk2-dev/focal 2.2.1-1 amd64
libvolk2-doc/focal,focal 2.2.1-1 all
libvolk2.2/now 2.2.1-2~ubuntu19.10.1~ppa1 amd64 [installed,local]
shack@radio:~/workspace/gr-satellites-3.3.0/build$ 

Now I don’t know how to proceed!

**Comment by daniestevez** [comment]
Dear Norbert,

Please include your report inside the message rather than as an attachment so that we can see it directly.

This seems a problem with your distribution rather than gr-satellites. Probably you can't build any other OOT modules from source. For some reason, `cmake` can't find GNU Radio when trying to build gr-satellites. The fact that it says `requested version 3.9` is strange. It should search version 3.8.

It seems you have a mixture of PPA packages and packages from focal, so maybe that's your problem.

**Comment by daniestevez** [comment]
Yes. If you don't have anything particularly valuable in that install, a clean install of Ubuntu 20.04 would probably save headaches.

Choice of distribution depends a lot on taste and experience. I'm a happy user of Gentoo and Arch, and use Debian testing for the gr-satellites buildroot server. But I wouldn't necessarily recommend these to a beginner.

**Comment by DL8LAQ** [comment]
The linux on my laptop is used only for gnuradio. I will do a clean install of 20.04 :-)

73, Norbert

**Comment by DL8LAQ** [comment]
A clean install of Ubuntu 20.04 and installation of gnuradio-companion and gr_satellites using miniconda did it! 73, Norbert
