### ISSUE TITLE
./test.sh error

### ISSUE THREAD

**Issue by N6RFM** [daniestevez/gr-satellites#184]
Hi Dani,

Possible recent updates may be associated with an error in the test.sh script, which hangs at S-NET A.

S-NET A
handler caught exception: name 'lut_crc' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/gateway.py", line 78, in eval
    try: self._callback(arg)
  File "/usr/local/lib/python3/dist-packages/satellites/snet_deframer.py", line 57, in handle_msg
    ltu_crc = np.flipud(lut_crc)
NameError: name 'lut_crc' is not defined
thread[thread-per-block[10]: <block snet_deframer(17)>]: SWIG director method error. Error detected when calling 'feval_p.eval'

Thanks,

Bob

**Comment by daniestevez** [comment]
Hi Bob,

Thanks! This is a bug. When I fixed the SALSAT CRC it seems I screwed the S-NET decoder and never checked it.

I'll fix it right away.
