### ISSUE TITLE
RuntimeError: invalid msg port in connect() or disconnect()

### ISSUE THREAD

**Issue by dagronplayer** [daniestevez/gr-satellites#186]
Hi, I am new to the GNU radio satellite. I have this error after i run the galassia.grc.   could anyone share with me what is the cause of this error? thank you!
Generating: '/home/kh/Downloads/gr-satellites-1.8.4/apps/galassia.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python2 -u /home/kh/Downloads/gr-satellites-1.8.4/apps/galassia.py

gr::log :DEBUG: correlate_access_code_tag_bb0 - Access code: c3aa6655
gr::log :DEBUG: correlate_access_code_tag_bb0 - Mask: ffffffff
Could not find port: out in:
in
system

Traceback (most recent call last):
  File "/home/kh/Downloads/gr-satellites-1.8.4/apps/galassia.py", line 183, in <module>
    main()
  File "/home/kh/Downloads/gr-satellites-1.8.4/apps/galassia.py", line 177, in main
    tb = top_block_cls(callsign=options.callsign, ip=options.ip, latitude=options.latitude, longitude=options.longitude, port=options.port, recstart=options.recstart)
  File "/home/kh/Downloads/gr-satellites-1.8.4/apps/galassia.py", line 87, in __init__
    self.msg_connect((self.satellites_u482c_decode_0, 'out'), (self.satellites_print_timestamp_0, 'in'))
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 59, in wrapped
    func(self, src.to_basic_block(), srcport, dst.to_basic_block(), dstport)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 131, in msg_connect
    self.primitive_msg_connect(*args)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5321, in primitive_msg_connect
    return _runtime_swig.top_block_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()
![image](https://user-images.githubusercontent.com/72313621/97456923-db842e00-196b-11eb-8480-384639252dbe.png)

**Comment by K4KDR** [comment]
Hello!  Is your .WAV file source an AUDIO file?  If so, use that "wav_48khz" flowgraph to play it.  Reconnect the original "UDP Source" block to receive the signal from the "wav_48khz" flowgraph.

This might not help with your error, but it is the correct way to feed an audio .WAV file to these gr-satellites flowgraphs with the "UDP Source" block as the input.

**Comment by dagronplayer** [comment]
> Hello! Is your .WAV file source an AUDIO file? If so, use that "wav_48khz" flowgraph to play it. Reconnect the original "UDP Source" block to receive the signal from the "wav_48khz" flowgraph.
> 
> This might not help with your error, but it is the correct way to feed an audio .WAV file to these gr-satellites flowgraphs with the "UDP Source" block as the input.

HI, thank you for your reply. you are right, it is a audio file.  after i run the wav_48khz, then follow by galassia.grc. the problem still the same.
![image](https://user-images.githubusercontent.com/72313621/97460792-ab3e8e80-196f-11eb-9481-132e684449de.png)
/home/kh/Pictures/Screenshot from 2020-10-28 22-47-10.png

**Comment by K4KDR** [comment]
You can DISABLE or delete the blocks "callsign", "recstart", "latitude", & "longitude" as they are not used in this flowgraph.  

Also, in case your system is not setup exactly right for IPv6, try with "ip" set to "127.0.0.1" in BOTH flowgraphs.

**Comment by dagronplayer** [comment]
> You can DISABLE or delete the blocks "callsign", "recstart", "latitude", & "longitude" as they are not used in this flowgraph.
> 
> Also, in case your system is not setup exactly right for IPv6, try with "ip" set to "127.0.0.1" in BOTH flowgraphs
still the same issue
![image](https://user-images.githubusercontent.com/72313621/97464364-66b4f200-1973-11eb-8d3e-93b3c61503d3.png)
![image](https://user-images.githubusercontent.com/72313621/97464393-6f0d2d00-1973-11eb-926d-aa73444aa555.png)

**Comment by daniestevez** [comment]
Hi @dagronplayer, thanks for your report.

Note that you're using a rather old and unmaintained release of gr-satellites. I would suggest you try out the current release v3.5.2. You might have more luck with that one.

Regarding your problem, my reading of the error you get is that the U842C FEC decode block doesn't have an out port, but it is [created here](https://github.com/daniestevez/gr-satellites/blob/60a7e28dcba8fa8c27569c63c4dc10aea85e5534/lib/u482c_decode_impl.cc#L77), and this used to work correctly when I used v1.8, so I'm not sure what is going on here.

**Comment by dagronplayer** [comment]
> Hi @dagronplayer, thanks for your report.
> 
> Note that you're using a rather old and unmaintained release of gr-satellites. I would suggest you try out the current release v3.5.2. You might have more luck with that one.
> 
> Regarding your problem, my reading of the error you get is that the U842C FEC decode block doesn't have an out port, but it is [created here](https://github.com/daniestevez/gr-satellites/blob/60a7e28dcba8fa8c27569c63c4dc10aea85e5534/lib/u482c_decode_impl.cc#L77), and this used to work correctly when I used v1.8, so I'm not sure what is going on here.

Thank you for your reply. I will try the new version.

**Comment by daniestevez** [comment]
Did gr-satellites v3.5.2 work correctly for you?

**Comment by dagronplayer** [comment]
> Did gr-satellites v3.5.2 work correctly for you?

Yes, it works.
