### ISSUE TITLE
--kiss_out option no longer works in v3.6.0

### ISSUE THREAD

**Issue by doctorvenables** [daniestevez/gr-satellites#193]
Hi Dani,
In the latest fetch (trying out Lucky7 imaging) the --kiss_out option has stopped working.

![image](https://user-images.githubusercontent.com/42719385/99184729-fbbe3600-273c-11eb-962b-78aabd3bc613.png)

Appears to be the case for both of the Rpi's I have gr-satellites installed on.

Otherwise gr_satellites works as normal i.e. take out the kss option and it decodes quite happily.
Mark

**Comment by daniestevez** [comment]
Thanks for noticing. It seems I broke that while reorganizing some code. I've just fixed this. It works for me now, but if it gives you any more trouble, please reopen this issue.
