### ISSUE TITLE
Master missing the CC11xx_remove_length block

### ISSUE THREAD

**Issue by Danieltajik** [daniestevez/gr-satellites#199]
Looks like the CC11xx_remove_length block was removed from master. Any reason for not including it? Or has its name changed?

**Comment by daniestevez** [comment]
See [the changelog](https://github.com/daniestevez/gr-satellites/blob/master/CHANGELOG.md#removed).

**Comment by Danieltajik** [comment]
Of course, this makes sense. I have personally used your blogpost here https://destevez.net/2018/12/decoding-reaktor-hello-world/  to work on development with my CC1125. Would it be possible for a quick update note on it? If not I can leave a comment mentioning that the block has changed. Thanks!

**Comment by daniestevez** [comment]
Yes, no problem. I have added a note at the end of the post.

**Comment by Danieltajik** [comment]
Thanks!
