### ISSUE TITLE
gr-lilacsat

### ISSUE THREAD

**Issue by alejoduque** [daniestevez/gr-satellites#2]
Hello when compiling from git sources the lilacsat decoder I get this error (all the mentioned deps are installed. Construct, FEH, gr-csp

https://github.com/bg2bhc/gr-lilacsat

Please let me know if I should follow some special directive to get it to compile. Gracias de antemano!

[a@dspstv build]$ make
[ 19%] Building CXX object lib/CMakeFiles/gnuradio-lilacsat.dir/afsk1200_tx_f_impl.cc.o
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc: In member function ‘virtual int gr::lilacs
at::afsk1200_tx_f_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_on[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x01, 0xFD};
                                                                     ^
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘22
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_off[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x00, 0xFD};
                                                                      ^
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘22
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/a/Documents/HK4ADJ/gnuradio-modules/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘25
’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
make[2]: *** [lib/CMakeFiles/gnuradio-lilacsat.dir/build.make:399: lib/CMakeFiles/gnuradio-lilacsat.dir/afsk1200_tx_f_impl.
cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: lib/CMakeFiles/gnuradio-lilacsat.dir/all] Error 2
make: *** [Makefile:139: all] Error 2

**Comment by daniestevez** [comment]
This is not a problem with gr-satellites, but with [gr-lilacsat](https://github.com/bg2bhc/gr-lilacsat) and it should be reported there (gr-lilacsat is not my own code).

In any case, it seems that the problem you have is that your compiler is taking some warnings as errors. Make sure that you're not using `-Werror`. That particular code is not even needed for gr-satellites, so you might remove it altogether.
