### ISSUE TITLE
Hi, I need some help with the limeSDR transceiver

### ISSUE THREAD

**Issue by dagronplayer** [daniestevez/gr-satellites#205]
I am trying to use LimeSDR to send the wave file of Gomx1 and decode it.  but it does not work . could someone tell me which part is wrong? thank you!

![Screenshot from 2020-12-12 12-55-21](https://user-images.githubusercontent.com/72313621/101976611-69487e00-3c79-11eb-94d2-896f4c726094.png)

this is transmitter 

![Screenshot from 2020-12-12 12-55-35](https://user-images.githubusercontent.com/72313621/101976616-736a7c80-3c79-11eb-8905-bd0146568f54.png)
this is receiver 
. 
![Screenshot from 2020-12-12 12-57-05](https://user-images.githubusercontent.com/72313621/101976627-909f4b00-3c79-11eb-93e6-2fb3c5f8c726.png)
this is output .  

if it worked, i should get below output .
![Screenshot from 2020-12-12 12-58-17](https://user-images.githubusercontent.com/72313621/101976642-b9bfdb80-3c79-11eb-951b-6ee355c3def8.png)

**Comment by daniestevez** [comment]
Hi,

When doing this kind of over-the-air test many things can go wrong. I think that your problem doesn't have so much to do with gr-satellites, but with something else in your test setup.
