### ISSUE TITLE
Transporter-1 satellites

### ISSUE THREAD

**Issue by daniestevez** [daniestevez/gr-satellites#224]
The following Amateur satellites were launched on the SpaceX F9 Transporter-1 mission:

* [x] UVSQ-Sat. Support already added beforehand.
* [x] SOMP 2b
* [x] IDEASSat. Support added shortly after launch
* [x] YUSAT 1. Signal has been analysed. A decoder is in progress.
* [ ] [ARCE 1A, 1B, 1C](http://www.amsatuk.me.uk/iaru/finished_detail.php?serialnum=643). IARU coordination only states S-band, with a variety of modulations. It would be very interesting to get a recording of these.

**Comment by jinsanko** [comment]
To: Daniel
Could you share the orbit info of YUSAT-1 and IDEASSat.
Thank.

**Comment by daniestevez** [comment]
@jinsanko I don't have more information than what is publicly available: the TLEs at Celestrak and Space-Track and the TLE lottery done by several people on Twitter and the librespace foundation forums.

**Comment by daniestevez** [comment]
The only thing that remains to do regarding this issue is to assign final NORAD numbers, since it doesn't seem likely that we'll get S-band recordings of the ARCE satellites soon.

**Comment by daniestevez** [comment]
After 1f1703d8ea4597c78ea2e2966ddafae8f039f2c9, only UVSQ-Sat and YUSAT-1 are missing NORAD IDs.

**Comment by daniestevez** [comment]
I just pushed ce157a1, which adds the NORAD ID for YUSAT-1.

Only USVQ-Sat is missing, and apparently it is [still too close to another object](https://twitter.com/ppapadeas/status/1359589350904848384) for a reliable Doppler identification.

**Comment by daniestevez** [comment]
Apparently a reliable TLE identification for UVSQ-Sat is still missing, but I'm going to release v3.7 regardless.

**Comment by daniestevez** [comment]
Closing, since we have already the final TLE for UVSQ-Sat and no data for the ARCE satellites.
