### ISSUE TITLE
GOMspace AX100 Deframer

### ISSUE THREAD

**Issue by luisguarnizo1234** [daniestevez/gr-satellites#268]
Hola Dani, espero estes muy bien.

Dani, actualmente estoy utilizando el bloque GOMsapce AX100 Deframer de gr-satellites en la opción de ASM + GOLAY, pero tengo una duda, revisando el manual del radio AX100 que está disponible en la página de GOMspace ellos mencionan que este radio agrega unas capas adicionales al campo de datos que está en la trama CSP; las cuales son una capa para HMAC, una capa para CRC, otra capa para Reed Salomon y una ultima capa para Randomización. Quería saber si me podrías dar alguna recomendación para decodificar esas tramas o si el bloque AX100 Deframer tiene la capacidad de identificar estas capas adicionales.

![image](https://user-images.githubusercontent.com/54753583/118900512-be4a8900-b8d6-11eb-8fc8-a8df762e4e5e.png)

**Comment by daniestevez** [comment]
Hola Luis. El bloque AX100 deframer maneja las capas de randomization y Reed Solomon FEC. El CRC supongo que se trata del CRC-32C de CSP. Hay algún bloque en gr-satellites para encargarse de ello, aunque la forma en la que distintos satélites usan este CRC varía (en aspectos como el endianness o si la cabecera CSP está incluida en el cálculo del CRC). Actualmente gr-satellites no incluye soporte para el HMAC.

**Comment by luisguarnizo1234** [comment]
1. Dani, gracias por tu respuesta. entonces con este bloque de GOMSpace AX100 Deframer en el modo ASM+GOLAY ya estaría realizando la parte de Randomization y Reed Solom FEC, quisiera saber que polinomio usa ese bloque para la randomization, según el manual del radio usan CCSDS h(x) = x8 + x7 + x5 + x3 + 1, es esté el mismo que usa el bloque?

2. cuando agrego el bloque de visualización de print CSP Header ya estaría ejecutando el CRC32 o debo implementar un bloque adicional para esto, porque cuando coloco el bloque de CSP Header ya estoy obteniendo datos en Hexadecimal y coinciden con el formato de la telemetría.

gracias Dani

**Comment by daniestevez** [comment]
1. Sí, es el mismo scrambler.
2. Hay un bloque llamado "Check CRC" para comprobar el CRC-32C de un paquete CSP.

**Comment by luisguarnizo1234** [comment]
Gracias Dani por la respuesta, Dani ahora que yo tengo mis tramas CSP decodificadas quisiera hacer una aplicación que me permita  recibir estos paquetes CSP en un cliente de la librería LIBCSP y enviarlos a un servidor con LIBCSP que los pueda entender. Tú tienes alguna recomendación para hacer esto?

gracias

**Comment by daniestevez** [comment]
Quizá es buena idea sacar los paquetes CSP de GNU Radio usando ZMQ.

**Comment by luisguarnizo1234** [comment]
Gracias Dani,

entiendo, yo ya tengo un ZMQ proxy corriendo entre un cliente y un servidor CSP, podría utilizar ese mismo ZQM por medio del proble ZQM PUB SINK
![image](https://user-images.githubusercontent.com/54753583/120041428-d6549380-bfcd-11eb-8fb7-903e626e1fd1.png)

**Comment by daniestevez** [comment]
Para enviar PDUs debes usar los "Message Sink". El endpoint que uses debe coincidir entre GNU Radio y el servidor CSP.

**Comment by luisguarnizo1234** [comment]
Gracias Dani, intentaré algo con ese bloque. Dani tú sabes que método de FEC se implementa en el bloque ASM + GOLAY, yo conozco que el AX100 cuenta con 12 bit para FEC, sin embargo, el manual no dice que método utiliza para este propósito

**Comment by daniestevez** [comment]
Es un código Golay(24,12).

**Comment by luisguarnizo1234** [comment]
Entiendo Dani, ya revisé la documentación que tienes sobre este método de FEC (https://destevez.net/2018/05/algebraic-decoding-of-golay2412/) y revisé el libro de the art of error correcting coding, pero me queda la duda de cómo obtuviste los parámetros de la matriz H, y que en el libro son diferentes a los que utilizas para implementar el código GOLAY
https://destevez.net/2018/05/algebraic-decoding-of-golay2412/

![image](https://user-images.githubusercontent.com/54753583/120386803-b800d780-c2ee-11eb-8a66-b664b30eb24f.png)

![image](https://user-images.githubusercontent.com/54753583/120386883-cd760180-c2ee-11eb-9082-82a1ae4ae018.png)

**Comment by daniestevez** [comment]
Puedes leer la nota al final de este post https://destevez.net/2016/09/decoding-gomx-1-telemetry/

**Comment by luisguarnizo1234** [comment]
Según veo en la nota, el orden de los bits de la matriz del libro debe invertirse, sin embargo no entiendo por qué la matriz del código tiene más bits que la matriz que la del libro

**Comment by daniestevez** [comment]
@luisguarnizo1234 podemos cerrar este issue?

**Comment by luisguarnizo1234** [comment]
Hola Daniel, muchas gracias. Si, creo que ya s3 puede cerrar
