### ISSUE TITLE
Investment consultance

### ISSUE THREAD

**Issue by Cript21** [daniestevez/gr-satellites#289]
This company is an online company in which the trade is being carried out with you investing in this company, you will be sending your money directed to the company's wallet, then the company will fund your account for you and the trade will take place.  With this company you can be earning money without going to work with anyone with you sitting at home. The investment trade will be carried out here in the company with the small amount invested with the company, so the company will be trading with this small amount and your money will increase in company's trading platform, after all successful trades have been completed, you will withdraw to your wallet address.
  It's good to know how bitcoin works, well Bitcoin trading is actually a digital means of making money online easily with the help of the right account manager and good trading software.  Forex trading is a life changing investment platform where you can invest a certain amount of money and it will yield profit for you weekly.  I just want you to eradicate the fear of losing from your mind and keep in mind the thrill of winning.
  I understand you're skeptical because it's your first time and I also want you to understand that action overcomes fear
  Honey, I'm a woman of God and I've been in this scheme for almost a decade and gat clients who are more skeptical, but now they're big investors and they're doing well 👌
  I need you to trust me because I believe in Karma, which means whatever you do to someone today will be done to you too
  But rest assured that you will get returns this time...you don't have to give up because quitters never win and winners never quit.
  The key to making progress is getting started.  Success does not come to you, "you go ahead, if you have the courage to be, you will have the courage to succeed.

**Comment by daniestevez** [comment]
Closing as spam.
