### ISSUE TITLE
./compile_hierarchical.sh: 3: ./compile_hierarchical.sh: grcc: not found

### ISSUE THREAD

**Issue by liiyuanshuai** [daniestevez/gr-satellites#34]
when run ./compile_hierarchical.sh 

./compile_hierarchical.sh: 3: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found
./compile_hierarchical.sh: 6: ./compile_hierarchical.sh: grcc: not found

**Comment by daniestevez** [comment]
You need to install `grcc`, which comes with `gnuradio-companion`.
