### ISSUE TITLE
kiss_server_sink: constructor mismatch

### ISSUE THREAD

**Issue by wgoltermann** [daniestevez/gr-satellites#342]
self.satellites_kiss_server_sink_0 = satellites.components.datasinks.kiss_server_sink('127.0.0.1', 8100, options="")
  File "/usr/local/lib/python3.10/site-packages/satellites/components/datasinks/kiss_server_sink.py", line 38, in __init__
    self.server = blocks.socket_pdu(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. gnuradio.blocks.blocks_python.socket_pdu(type: str, addr: str, port: str, MTU: int = 10000, tcp_no_delay: bool = False)

An easy temporary fix is done by editing the generated py file and changing the port value (8100) to a string.

**Comment by daniestevez** [comment]
Thanks for spotting the bug. I've created a pull request (#343) that I believe fixes the problem. Can you test this pull request and check if the problem disappears?
