### ISSUE TITLE
unable to  compile_hierarchical.sh 

### ISSUE THREAD

**Issue by liiyuanshuai** [daniestevez/gr-satellites#35]
$ . ./compile_hierarchical.sh 
Block key "satellites_ao40_deinterleaver" not found
Block key "satellites_ao40_rs_decoder" not found
Block key "satellites_ao40_syncframe" not found
Validation failed:

Block - ccsds_descrambler_0 - CCSDS descrambler(ccsds_descrambler):
	Source - out(out):
		Port is not connected.

Block - pad_sink_0 - Pad Sink(pad_sink):
	Sink - in(in):
		Port is not connected.

Block - pad_source_0 - Pad Source(pad_source):
	Source - out(0):
		Port is not connected.
Error during file compilation.
Block key "satellites_ao40_deinterleaver_soft" not found
Block key "satellites_ao40_rs_decoder" not found
Block key "satellites_ao40_syncframe_soft" not found
Validation failed:

Block - ccsds_descrambler_0 - CCSDS descrambler(ccsds_descrambler):
	Source - out(out):
		Port is not connected.

Block - pad_sink_0 - Pad Sink(pad_sink):
	Sink - in(in):
		Port is not connected.

Block - pad_source_0 - Pad Source(pad_source):
	Source - out(0):
		Port is not connected.
Error during file compilation.
Block key "satellites_fixedlen_tagger" not found
Validation failed:

Block - blocks_tagged_stream_to_pdu_0_0_0 - Tagged Stream to PDU(blocks_tagged_stream_to_pdu):
	Sink - in(0):
		Port is not connected.

Block - digital_correlate_access_code_tag_bb_0_0_0 - Correlate Access Code - Tag(digital_correlate_access_code_tag_xx):
	Source - out(0):
		Port is not connected.
Error during file compilation.
Block key "satellites_fixedlen_tagger" not found
Validation failed:

Block - blocks_unpacked_to_packed_xx_0 - Unpacked to Packed(blocks_unpacked_to_packed_xx):
	Sink - in(0):
		Port is not connected.

Block - digital_correlate_access_code_tag_bb_0_0_0 - Correlate Access Code - Tag(digital_correlate_access_code_tag_xx):
	Source - out(0):
		Port is not connected.

**Comment by daniestevez** [comment]
Have you installed gr-satellites successfully before trying to compile the hierarchical blocks?

The `Block key "satellites_ao40_deinterleaver" not found` error points to some gr-satellites blocks not properly installed on your system.
