### ISSUE TITLE
Unable to start gr_satellites - TypeError: function() argument 1 must be code, not str

### ISSUE THREAD

**Issue by stefanpi1** [daniestevez/gr-satellites#363]
Hi,
after buildng gr_satellites V4.6.0 from source without any problems, I get the following error-message when staring the program.
Any ideas, what could have gone wrong?
Any help very appreciated!
73,
Stefan/oe6isp

pi@raspberrypi:/usr/bin $ ./gr_satellites -h
Traceback (most recent call last):t-packages/satellites/telemetry/cute_70cm.py", line 86, in <module>
  File "./gr_satellites", line 16, in <module>
    import satellites.corement 1 must be code, not str
  File "/usr/local/lib/python3/dist-packages/satellites/__init__.py", line 49, in <module>
    from .adsb_kml import adsb_kml
  File "/usr/local/lib/python3/dist-packages/satellites/adsb_kml.py", line 15, in <module>
    from .telemetry import gomx_3 as tlm
  File "/usr/local/lib/python3/dist-packages/satellites/telemetry/__init__.py", line 30, in <module>
    from .cute_70cm import cute_70cm
  File "/usr/local/lib/python3/dist-packages/satellites/telemetry/cute_70cm.py", line 86, in <module>
    class FswParserState(Enum):
TypeError: function() argument 1 must be code, not str
pi@raspberrypi:/usr/bin $

**Comment by daniestevez** [comment]
Hi Stefan,

A couple of things:

1. Can you paste again the output [like this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) for proper formatting. Some things are being mangled and I'm not sure if I'm reading it correctly (in particular the `import satellites.corement 1 must be code, not str` message).
2. What version of python-construct do you have installed?

**Comment by stefanpi1** [comment]
Thanks a lot for your quick reply, which lead me to the solution immediately. I had construct 2.8 installed - upgraded to 2.10 and problem was gone.

(the messages are formatted this way, even when window is maximized. dont know why)

**Comment by daniestevez** [comment]
Perfect. Glad that you could solve this easily.
