### ISSUE TITLE
Reed-Solomon decode fail

### ISSUE THREAD

**Issue by shakthivels300** [daniestevez/gr-satellites#389]
Hi thank you so much for this repo
I didn't get any error during installation of gr-satellite with branch maint-3.8 but when i run this,
command---->gr_satellites FUNcube-1 --wavfile ~/gr-satellites/satellite-recordings/ao73.wav --samp_rate 48e3
I am getting this error,
Error---> gr::log :DEBUG: decode_rs0 - Reed-Solomon decode fail (interleaver path 0)
i am not getting what the problem is.
Any help is appreciable
       **Sorry for the inconvenience .Problem solved by running volk_profile #217 @daniestevez   you may close this**      

Thanks

![image](https://user-images.githubusercontent.com/77143655/181880265-b6fc857d-12f4-4026-bc41-1bc0549c7c30.png)

![image](https://user-images.githubusercontent.com/77143655/181880281-78e56055-4b31-4434-979d-afebb1a07f01.png)

**Comment by daniestevez** [comment]
Glad you found the fix in #217. Closing.
