### ISSUE TITLE
""ImportError: libgnuradio-satellites.so.5.1.0git: cannot open shared object file: No such file or directory""  why am i getting this warning

### ISSUE THREAD

**Issue by planeksever** [daniestevez/gr-satellites#403]

**Comment by daniestevez** [comment]
Can you give more information about what you're doing (full console log, etc.)?

**Comment by planeksever** [comment]
> 
i just play a grc file with gnradio but gr-satellites nothing works, it gives the error i specified

**Comment by daniestevez** [comment]
Can you describe how you installed gr-satellites and what system (operating system, etc.) your are using?
Where the libgnuradio-satellites.so.5.1.0git file was installed to?

**Comment by daniestevez** [comment]
Closing, since this issue needs more information about the problem and has been for a month without progress. Feel free to reopen to give more information.
