### ISSUE TITLE
FUNcube decoders not working on V5.1.1

### ISSUE THREAD

**Issue by dw9ilx** [daniestevez/gr-satellites#430]
I updated my g-satellites to the latest available version, Now the decoder for FUNcube satellites yield Reed-Solomon Fail result. 

It both happens in UDP source and the test.sh recordings.

**Comment by daniestevez** [comment]
Can you check if you're affected by [this bug in libvolk](https://github.com/daniestevez/gr-satellites#known-problems)?

Can you give more details about your system and how you've installed gr-satellites? If you built gr-satellites from source, do the unit tests (`ctest` or `make test`) pass?

**Comment by daniestevez** [comment]
Closing due to no additional information. Feel free to re-open.
