### ISSUE TITLE
AO-73 decoder not recongising frame types

### ISSUE THREAD

**Issue by LouisTimperley** [daniestevez/gr-satellites#44]
Hi Daniel,
I have recently downloaded your gr-satellites decoders- a really great set of work!
However I have found that when testing the A0-73 sample recording into the AO-73 decoder, it is not recognising the frame type, the frame type being a typical WO-10 in the sample provided: (https://github.com/daniestevez/satellite-recordings/tree/6f36d42dc557a8121c76e08207a06dcf46d969de).
Also are you aware of any filtering that has been applied to the sample-  other sample files, from the funcube website don't appear to work?
It would be great if you had any pointers on how to get around this
Again great work on gr-satellites and kind regards
Louis

**Comment by daniestevez** [comment]
Thanks for the report,
This is a indeed a bug. I have fixed it in  2eb31d4
Other files might use a different BFO frequency.
