### ISSUE TITLE
Specific flowgraph in gr satellites

### ISSUE THREAD

**Issue by Foxiks** [daniestevez/gr-satellites#538]
Hello! I would like to clarify if I can add my grc file to gr-satellites for a specific satellite? What should I add to the project so that when calling gr_satellites and specifying the name of the satellite, a certain flowgraph will work?

**Comment by daniestevez** [comment]
Hi, GRC files for a specific satellite go into `examples/satellites`. This isn't tied in any way to the `gr_satellites` CLI app or the Satellite Decoder GRC block. In order for a specific satellite to work with `gr_satellites` and the Satellite Decoder block it is necessary to:
* Have the required demodulator and deframer in `python/components/demodulators` and `python/components/deframers`.
* Define these in the SatYAML syntax in `python/satyaml/satyaml.py`.
* Have a `.yml` file for the satellite in `python/satyaml`.
* Hook up the demodulator and deframer blocks in `python/core/gr_satellites_flowgraph.py`.

**Comment by Foxiks** [comment]
Thanks!
