### ISSUE TITLE
Missing KISS blocks (nrzi decode, hdlc framer)

### ISSUE THREAD

**Issue by Zanobos** [daniestevez/gr-satellites#54]
Hi Daniel,
I was checking the "generic_9k6_fsk_ax25" decoder, however when I opened the project two blocks were missing: 
- kiss nrzi decode
- kiss hdlc deframer

I made a rapid check in the available blocks: https://github.com/daniestevez/gr-satellites/tree/master/grc and I found only two "KISS" related blocks, however not the needed ones.
Can you help me?
Best,
Andrea

**Comment by daniestevez** [comment]
Thank you for reporting this.

I already noticed and fixed this problem when porting to GNU Radio 3.8, but then forgot to fix it in the master branch. It is now fixed in c0a7d9c738b4fe3cc17ccb9fb33b5a7744af0097.
