### ISSUE TITLE
Norad ID for facsat_1.grc 

### ISSUE THREAD

**Issue by cswiger** [daniestevez/gr-satellites#58]
Tiniest of typos - facsat_1.grc has <value>43722</value> in the Telemetry Forwarder which is CENTAURI 2.   facsat-1 is 43721.

**Comment by daniestevez** [comment]
Thanks for noticing. I have just fixed this in 3e93d9a47e3479a67cdc63d5bf5277e0169775ac (maint-3.7) and 9b258fc356eb8fd8ccec579c60081ff961366a93 (maint-3.8).
