### ISSUE TITLE
Attribute error happens when I want to make a new block by OOT module.

### ISSUE THREAD

**Issue by buaawang** [daniestevez/gr-satellites#63]
Dear Daniestevez,

I want to learn how to generate a new block, I have alreay follow the gr-tutorial from the guide book from Gnuradio Website. As I am tracking the satellite which is using the Gomspace tranceiver, I want to change something in the block. So I usr the gr-modtool to build a new one. I have change the .cpp, .h, and the .xml files in the floder. It can be built and install well. But when I use it to run, Something happened like the followings. I have used the sudo `make install` and `sudo ldconfig`. Besides, I can run your softwares very well.

  File "/home/wang/study-gnuradio/graduate/top_block.py", line 95, in __init__
    self.shiwang_my_decode_0 = shiwang.my_decode(False, 1, 1)
AttributeError: 'module' object has no attribute 'my_decode'

Regards,

Shiwang Xing,
Beihang University, Micro-Satellite Technology Lab.

**Comment by daniestevez** [comment]
Dear Shiwang Xing,
This doesn't seem an issue with gr-satellites, so I'm closing it. I suggest you look for advice in a more appropriate place, such as the GNU Radio mailing list.
