### ISSUE TITLE
How to install and apply these files? I'm a novice. Thank you

### ISSUE THREAD

**Issue by hanyelei** [daniestevez/gr-satellites#65]
How to install and apply these files? I'm a novice. Thank you

**Comment by daniestevez** [comment]
Could you please be more specific in your question? There are installation instructions in the README and the wiki.

**Comment by hanyelei** [comment]
Thank you for your reply. I use USRP B200 to prepare a platform that can receive satellite telemetry data. Receiving frequency 430-450mhz, demodulation mode BPSK, rate 9600. But since it's the first time to use this board, I'm here to ask for advice

**Comment by daniestevez** [comment]
None of what you said relates to gr-satellites directly. Do you have GNU Radio installed and are you able to use your B200 in GNU Radio? If yes, then install gr-satellites following the instructions. If not, then these are requirements you need to meet before using gr-satellites.

**Comment by hanyelei** [comment]
Yes, I use GNU radio

**Comment by hanyelei** [comment]
Download the GR file and run the following installation steps directly?
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

**Comment by daniestevez** [comment]
That's what I have written in the instructions, yes.

Please read the complete README file, have a look at the [wiki](https://github.com/daniestevez/gr-satellites/wiki) also in case that helps, and then after actually trying to install this on your own, if you find some problem that you can report in a concrete way, please come back here.

**Comment by hanyelei** [comment]
thanks

**Comment by hanyelei** [comment]
Does GR use gnuradio version 3.8? Is the other version OK? For example, 3.7

**Comment by daniestevez** [comment]
If GR == gr-satellites, this is described in the README.

**Comment by daniestevez** [comment]
After a couple weeks with no additional feedback I'm closing this, since no particular bug was reported.
