### ISSUE TITLE
SMOG-P/ATL-1 rms agc couses crashes.

### ISSUE THREAD

**Issue by nepeee** [daniestevez/gr-satellites#69]
If the source goes complete silence the scripts crashes with the following error:
buffer.h:193: unsigned int gr::buffer::index_add(unsigned int, unsigned int): Assertion `s < d_bufsize' failed.

For debugging i disabled all but one demod paths and removed everything after the Clock recovery block and done various tests:
- removed the Clock recovery block (fixes the issue)
- pypassed the dc blocker block (fixes the issue)
- removed the divide rms path (fixes the issue)
- changed the Add const block value to 1e-8 (fixes the issue partially, still some random crashes)
- changed the Add const block value to 1e-6 (fixes the issue, stuck with this solution right now)

It seems that the Clock recovery block causing the crash if the agc part is active.

**Comment by nepeee** [comment]
I think i found the issue. For the 1250 baud demod the RMS block is connected to the DC Blocker output but strangely for the other demods its connected to the low pass filter. I quickly changed the other demods(DC Blocker->RMS block) and it seems that it solved the problem.

**Comment by daniestevez** [comment]
You are right! The mistake in the connections was an oversight on my part.Thanks.  I've just fixed it.
