### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by ma-kin-79** [daniestevez/gr-satellites#72]
I am attempting to use gnuradio-companion and I have been having issues with compiling While attempting to run: ./compile_hierarchical.sh in my terminal, I have been receiving compilation and load errors due to invalid flowgraphs. I am using GNU Radio 3.8. Here is a copy of my terminal:

slite:~/gr-satellites$ ./compile_hierarchical.sh 
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder.grc
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder.grc: Flowgraph invalid
Compilation error

(the Load Error is consistent all throughout the compilation attempt).
I am using the master branch (the 3.8 branch). Due to this, I am unable to use the necessary blocks in the companion; I am just shown "Missing Block". Do you have any suggestions regarding the compilation error?

**Comment by daniestevez** [comment]
The ao40_fec_decoder.grc block is deprecated and used other deprecated blocks which no longer exist, hence the error. I have just removed this block in ec7a4aeac1d0e793eb6f34f2a4d1cf1de2eb3a6a, but in any case I think that the execution of `compile_hierarchical.sh` should have proceeded correctly despite this error.

**Comment by daniestevez** [comment]
You shouldn't get errors for the other blocks. Could you please copy the full output?

**Comment by ma-kin-79** [comment]
Here is the output from my terminal:
 
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ccsds_descrambler.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/ccsds_descrambler.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder.grc
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder.grc: Flowgraph invalid
Compilation error
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder_soft.grc
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/ao40_fec_decoder_soft.grc: Flowgraph invalid
Compilation error
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ccsds_descrambler.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/ccsds_descrambler.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/ccsds_viterbi.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/ccsds_viterbi.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/pn9_scrambler.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/pn9_scrambler.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/rms_agc.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/rms_agc.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/si4463_scrambler.grc
>>> Converting from XML
>>> Generating: /home/slite/.grc_gnuradio/si4463_scrambler.py
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/smogp_short_fec_decoder_soft.grc
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/smogp_short_fec_decoder_soft.grc: Flowgraph invalid
Compilation error
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu.grc
>>> Converting from XML
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu.grc: Flowgraph invalid
Compilation error
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu_packed.grc
>>> Converting from XML
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu_packed.grc: Flowgraph invalid
Compilation error
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
	/home/slite/.grc_gnuradio
	/usr/local/share/gnuradio/grc/blocks

>>> Loading: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu_soft.grc
>>> Load Error: /home/slite/gr-satellites/apps/hierarchical/sync_to_pdu_soft.grc: Flowgraph invalid
Compilation error

The errors are consistent throughout the process.

**Comment by daniestevez** [comment]
Could you please open `/home/slite/gr-satellites/apps/hierarchical/sync_to_pdu_soft.grc` with `gnuradio-companion` and check if it reports any additional errors?

**Comment by ma-kin-79** [comment]
[sync_to_pdu_soft.pdf](https://github.com/daniestevez/gr-satellites/files/4167247/sync_to_pdu_soft.pdf)

**Comment by ma-kin-79** [comment]
The output indicates that the satellites_fixedlen_tagger is a missing block.

**Comment by daniestevez** [comment]
The satellites_fixedlen_tagger should have been installed as part of your gr-satellites installation.

Have you successfully installed gr-satellites by following the [instructions in the README](https://github.com/daniestevez/gr-satellites#installation)?

If so, does the file `/usr/local/share/gnuradio/grc/blocks/satellites_fixedlen_tagger.block.yml` exist in your system?

**Comment by N2YQO** [comment]
![20200219_001226](https://user-images.githubusercontent.com/61221361/74804739-15fedc80-52af-11ea-9887-efbcbb003921.jpg)
![Uploading 20200219_001420.jpg…]()
I am having the same issues. It won't show me anything in the apps. Seems as if all flow graphs are empty.

**Comment by daniestevez** [comment]
> I am having the same issues. It won't show me anything in the apps. Seems as if all flow graphs are empty.

Hi, I'm sorry but this doesn't have much to do with the original poster issues.

Your problem is that you have GNU Radio 3.7.13.4 installed on your system, while the branch of gr-satellites you are using (most likely the master branch) supports only GNU Radio 3.8 or 3.9.

**Comment by ma-kin-79** [comment]
@daniestevez Thank you for helping me resolve this issue. It is now fixed and running properly. I had to move those files to the right directory.
