### ISSUE TITLE
Hello, everyone. I'd like to ask you some questions. Please give me some advice

### ISSUE THREAD

**Issue by hanyelei** [daniestevez/gr-satellites#74]
I have a USRP B200 board. I want to complete the following functions. What should I do? Thank you
1、Receive 420mhz-450mhz signal
2、Modulation mode BPSK, data rate 1200-9600 bit / s, scrambling polynomial  x17 + x12 + 1 G3RUH
In addition, there are many examples in GR satellite, but as a beginner, there are many people who don't understand it. For example, the il01 input is UDP, and B200 can't be implemented. How can I modify it on this basis. Thanks again

**Comment by daniestevez** [comment]
This is a duplicate of #75
