### ISSUE TITLE
Missing "sudo ldconfig" after sudo make install 

### ISSUE THREAD

**Issue by f6bvp** [daniestevez/gr-satellites#94]
Hi Daniel,
Congratulation for the new gr-satellite release.
It looks fabulous !
However after successful install of gr-satellite I tried the example :
bernard@f6bvp-Ubuntu:~/GNU-Radio/gr-satellites$ gr_satellites FUNcube-1 --wavfile satellite-recordings/ao73.wav --samp_rate 48e3
Traceback (most recent call last):
 .......
I understood that I forgot to run 
sudo ldconfig
after 
sudo make
while installing gr-satellite.

I am not sure this is specified and you probably want to add this in the installation page.
https://gr-satellites.readthedocs.io/en/latest/installation.html

73 de Bernard, f6bvp
https://radiotelescopelavillette.wordpress.com/

**Comment by daniestevez** [comment]
Hi Bernarnd,
Thanks for all the suggestions about the documentation. I'll go and fix these.
